<?php

namespace Upsoftware\Svarium\Services\Api;

use Illuminate\Routing\Route as LaravelRoute;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;
use RuntimeException;

class OpenApiGenerator
{
    /**
     * @return array<string, mixed>
     */
    public function generate(?string $serverUrl = null): array
    {
        $prefix = $this->apiPrefix();
        $paths = [];

        foreach (Route::getRoutes() as $route) {
            if (! $route instanceof LaravelRoute) {
                continue;
            }

            $uri = trim((string) $route->uri(), '/');
            if (! $this->isApiRoute($uri, $prefix)) {
                continue;
            }

            if ($this->isExcludedRoute($uri)) {
                continue;
            }

            $path = '/'.$uri;
            $methods = $this->normalizeMethods($route->methods());

            foreach ($methods as $method) {
                $paths[$path][strtolower($method)] = $this->buildOperation($route, $method, $path, $prefix);
            }
        }

        ksort($paths);
        foreach ($paths as &$operations) {
            ksort($operations);
        }
        unset($operations);

        return [
            'openapi' => '3.0.3',
            'info' => [
                'title' => $this->title(),
                'version' => $this->version(),
                'description' => 'Auto-generated by Svarium from registered Laravel routes.',
            ],
            'servers' => [
                ['url' => $serverUrl ?: $this->serverUrl()],
            ],
            'paths' => $paths,
            'components' => [
                'securitySchemes' => [
                    'bearerAuth' => [
                        'type' => 'http',
                        'scheme' => 'bearer',
                        'bearerFormat' => strtoupper($this->authDriver()),
                    ],
                ],
            ],
        ];
    }

    public function generateAndStore(?string $targetPath = null, bool $pretty = true): string
    {
        $path = $targetPath ?: $this->resolvedStoragePath();
        $directory = dirname($path);

        if (! is_dir($directory) && ! @mkdir($directory, 0755, true) && ! is_dir($directory)) {
            throw new RuntimeException('Unable to create directory for OpenAPI file: '.$directory);
        }

        $json = json_encode(
            $this->generate(),
            ($pretty ? JSON_PRETTY_PRINT : 0) | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES
        );

        if (! is_string($json)) {
            throw new RuntimeException('Failed to encode OpenAPI spec to JSON.');
        }

        file_put_contents($path, $json);

        return $path;
    }

    public function resolvedStoragePath(): string
    {
        $configured = trim((string) config('upsoftware.api.docs.storage_path', ''));
        if ($configured === '') {
            return storage_path('app/svarium/openapi.json');
        }

        if ($this->isAbsolutePath($configured)) {
            return $configured;
        }

        return base_path($configured);
    }

    /**
     * @return array<int, string>
     */
    protected function normalizeMethods(array $methods): array
    {
        $filtered = [];

        foreach ($methods as $method) {
            $method = strtoupper(trim((string) $method));
            if ($method === '' || in_array($method, ['HEAD', 'OPTIONS'], true)) {
                continue;
            }

            $filtered[] = $method;
        }

        $filtered = array_values(array_unique($filtered));
        sort($filtered);

        return $filtered;
    }

    /**
     * @return array<string, mixed>
     */
    protected function buildOperation(LaravelRoute $route, string $method, string $path, string $prefix): array
    {
        $parameters = $this->pathParameters($path);
        $middleware = array_values(array_filter(array_map('strval', $route->gatherMiddleware())));
        $requiresAuth = $this->requiresAuth($middleware);
        $tag = $this->tagForPath($path, $prefix);

        $responses = [
            '200' => [
                'description' => 'Success',
            ],
        ];

        if ($requiresAuth) {
            $responses['401'] = ['description' => 'Unauthorized'];
            $responses['403'] = ['description' => 'Forbidden'];
        }

        return [
            'summary' => $this->summary($route, $method, $path),
            'operationId' => $this->operationId($route, $method, $path),
            'tags' => [$tag],
            'parameters' => $parameters,
            'responses' => $responses,
            'security' => $requiresAuth ? [['bearerAuth' => []]] : [],
            'x-laravel' => [
                'route_name' => (string) ($route->getName() ?? ''),
                'action' => (string) $route->getActionName(),
                'middleware' => $middleware,
            ],
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    protected function pathParameters(string $path): array
    {
        preg_match_all('/\{([^}]+)\}/', $path, $matches);
        $names = $matches[1] ?? [];

        $params = [];

        foreach ($names as $nameRaw) {
            $name = rtrim(trim((string) $nameRaw), '?');
            if ($name === '') {
                continue;
            }

            $params[] = [
                'name' => $name,
                'in' => 'path',
                'required' => true,
                'schema' => [
                    'type' => 'string',
                ],
            ];
        }

        return $params;
    }

    protected function summary(LaravelRoute $route, string $method, string $path): string
    {
        $name = trim((string) ($route->getName() ?? ''));
        if ($name !== '') {
            return $name;
        }

        return sprintf('%s %s', strtoupper($method), $path);
    }

    protected function operationId(LaravelRoute $route, string $method, string $path): string
    {
        $name = trim((string) ($route->getName() ?? ''));
        if ($name !== '') {
            return (string) Str::of($name)
                ->replace([':', '.'], '_')
                ->snake()
                ->toString();
        }

        return (string) Str::of($method.'_'.trim($path, '/'))
            ->replace(['/', '-', '{', '}', '.'], '_')
            ->replaceMatches('/_+/', '_')
            ->trim('_')
            ->snake()
            ->toString();
    }

    protected function tagForPath(string $path, string $prefix): string
    {
        $normalized = trim($path, '/');
        $prefix = trim($prefix, '/');

        if ($prefix !== '' && Str::startsWith($normalized, $prefix.'/')) {
            $normalized = substr($normalized, strlen($prefix) + 1);
        } elseif ($prefix !== '' && $normalized === $prefix) {
            $normalized = '';
        }

        $first = trim((string) Str::before($normalized, '/'));
        if ($first === '') {
            return 'General';
        }

        return (string) Str::of($first)
            ->replace(['-', '_'], ' ')
            ->title()
            ->toString();
    }

    protected function requiresAuth(array $middleware): bool
    {
        foreach ($middleware as $item) {
            $normalized = strtolower(trim($item));
            if ($normalized === '') {
                continue;
            }

            if (
                Str::startsWith($normalized, 'auth')
                || Str::contains($normalized, 'sanctum')
                || Str::contains($normalized, 'passport')
                || Str::contains($normalized, 'jwt')
            ) {
                return true;
            }
        }

        return false;
    }

    protected function isApiRoute(string $uri, string $prefix): bool
    {
        if ($prefix === '') {
            return false;
        }

        return $uri === $prefix || Str::startsWith($uri, $prefix.'/');
    }

    protected function isExcludedRoute(string $uri): bool
    {
        $docsPath = trim((string) config('upsoftware.api.docs.path', 'api/docs'), '/');
        $specPath = trim((string) config('upsoftware.api.docs.spec_path', 'api/openapi.json'), '/');

        if ($docsPath !== '' && ($uri === $docsPath || Str::startsWith($uri, $docsPath.'/'))) {
            return true;
        }

        if ($specPath !== '' && ($uri === $specPath || Str::startsWith($uri, $specPath.'/'))) {
            return true;
        }

        return false;
    }

    protected function apiPrefix(): string
    {
        $prefix = trim((string) config('upsoftware.api.prefix', 'api/v1'), '/');

        return $prefix !== '' ? $prefix : 'api/v1';
    }

    protected function authDriver(): string
    {
        $driver = trim((string) config('upsoftware.api.auth.driver', 'sanctum'));

        return $driver !== '' ? $driver : 'sanctum';
    }

    protected function title(): string
    {
        $configured = trim((string) config('upsoftware.api.docs.title', ''));
        if ($configured !== '') {
            return $configured;
        }

        $appName = trim((string) config('app.name', 'Svarium'));

        return $appName.' API';
    }

    protected function version(): string
    {
        $configured = trim((string) config('upsoftware.api.docs.version', ''));
        if ($configured !== '') {
            return $configured;
        }

        return trim((string) config('app.version', '1.0.0')) ?: '1.0.0';
    }

    protected function serverUrl(): string
    {
        $configured = trim((string) config('upsoftware.api.docs.server_url', ''));
        if ($configured !== '') {
            return rtrim($configured, '/');
        }

        return rtrim((string) config('app.url', ''), '/');
    }

    protected function isAbsolutePath(string $path): bool
    {
        if ($path === '') {
            return false;
        }

        if (str_starts_with($path, '/')) {
            return true;
        }

        return preg_match('/^[A-Za-z]:[\\\\\\/]/', $path) === 1;
    }
}

